In [1]:
import pandas as pd
import numpy as np

# ==========================================================
# Stage 2 — Main Benchmark Comparison
# Main metrics: Precision, Recall, F1-score, AUPRC
# Values are stored directly as percentages.
# Missing values are kept as np.nan and displayed as "-".
# ==========================================================

data = [
    # Model, Dataset, Precision, Recall, F1, AUPRC, Source/Status, Note

    # -------------------------
    # Proposed model: DeepSKAN
    # WaveletKAN + Attention + DeepSVDD
    # -------------------------
    ["DeepSKAN", "SWaT", 93.52, 96.69, 95.08, 98.10, "Ours", "Final proposed model"],
    ["DeepSKAN", "MSL",  91.58, 93.27, 92.42, 90.47, "Ours", "Final proposed model"],
    ["DeepSKAN", "SMAP", 89.24, 69.96, 78.43, 87.36, "Ours", "Final proposed model"],

    # -------------------------
    # DeepSVDD alone
    # -------------------------
    ["DeepSVDD", "SWaT", 26.11, 84.73, 39.92, 24.29, "Reproduced", "EasyTSAD reproduction"],
    ["DeepSVDD", "MSL",  91.80, 65.67, 76.57, 77.61, "Reproduced", "EasyTSAD reproduction"],
    ["DeepSVDD", "SMAP", 13.63, 89.63, 23.65, 15.23, "Reproduced", "PR-AUC used as AUPRC"],

    # -------------------------
    # KAN-AD
    # -------------------------
    ["KAN-AD", "SWaT", 73.05, 89.59, 74.15, 69.33, "Reproduced", "Standalone KAN-AD"],
    ["KAN-AD", "MSL",  53.10, 66.73, 46.33, 36.67, "Reproduced", "Standalone KAN-AD"],
    ["KAN-AD", "SMAP", 91.59, 44.91, 57.04, 50.15, "Reproduced", "Standalone KAN-AD"],

    # -------------------------
    # DLinear
    # -------------------------
    ["DLinear", "SWaT", 95.53, 95.77, 95.65, 97.98, "Reproduced", "EasyTSAD implementation"],
    ["DLinear", "MSL",  90.95, 86.60, 88.72, 91.48, "Reproduced", "EasyTSAD implementation"],
    ["DLinear", "SMAP", 71.80, 71.10, 71.45, 80.77, "Reproduced", "EasyTSAD implementation"],

    # -------------------------
    # LSTM Autoencoder
    # -------------------------
    ["LSTM-AE", "SWaT", 94.05, 79.33, 86.06, 86.70, "Reproduced", "EasyTSAD implementation"],
    ["LSTM-AE", "MSL",  29.41, 75.55, 42.34, 31.59, "Reproduced", "EasyTSAD implementation"],
    ["LSTM-AE", "SMAP", 66.57, 52.92, 58.97, 55.13, "Reproduced", "EasyTSAD implementation"],

    # -------------------------
    # KARMAD
    # -------------------------
    ["KARMAD", "SWaT", 90.68, 77.96, 83.84, 86.65, "Reproduced", "EasyTSAD implementation based on KARMAD paper"],
    ["KARMAD", "MSL",  85.54, 80.67, 83.03, 83.11, "Reproduced", "EasyTSAD implementation based on KARMAD paper"],
    ["KARMAD", "SMAP", 94.50, 54.74, 69.32, 69.37, "Reproduced", "EasyTSAD implementation based on KARMAD paper"],
]

df_stage2 = pd.DataFrame(
    data,
    columns=["Model", "Dataset", "Precision", "Recall", "F1", "AUPRC", "Source", "Note"]
)

df_stage2

,Model,Dataset,Precision,Recall,F1,AUPRC,Source,Note
0,DeepSKAN,SWaT,93.52,96.69,95.08,98.10,Ours,Final proposed model
1,DeepSKAN,MSL,91.58,93.27,92.42,90.47,Ours,Final proposed model
2,DeepSKAN,SMAP,89.24,69.96,78.43,87.36,Ours,Final proposed model
3,DeepSVDD,SWaT,26.11,84.73,39.92,24.29,Reproduced,EasyTSAD reproduction
4,DeepSVDD,MSL,91.80,65.67,76.57,77.61,Reproduced,EasyTSAD reproduction
5,DeepSVDD,SMAP,13.63,89.63,23.65,15.23,Reproduced,PR-AUC used as AUPRC
6,KAN-AD,SWaT,73.05,89.59,74.15,69.33,Reproduced,Standalone KAN-AD
7,KAN-AD,MSL,53.10,66.73,46.33,36.67,Reproduced,Standalone KAN-AD
8,KAN-AD,SMAP,91.59,44.91,57.04,50.15,Reproduced,Standalone KAN-AD
9,DLinear,SWaT,95.53,95.77,95.65,97.98,Reproduced,EasyTSAD implementation
10,DLinear,MSL,90.95,86.60,88.72,91.48,Reproduced,EasyTSAD implementation
11,DLinear,SMAP,71.80,71.10,71.45,80.77,Reproduced,EasyTSAD implementation
12,LSTM-AE,SWaT,94.05,79.33,86.06,86.70,Reproduced,EasyTSAD implementation
13,LSTM-AE,MSL,29.41,75.55,42.34,31.59,Reproduced,EasyTSAD implementation
14,LSTM-AE,SMAP,66.57,52.92,58.97,55.13,Reproduced,EasyTSAD implementation
15,KARMAD,SWaT,90.68,77.96,83.84,86.65,Reproduced,EasyTSAD implementation based on KARMAD paper
16,KARMAD,MSL,85.54,80.67,83.03,83.11,Reproduced,EasyTSAD implementation based on KARMAD paper
17,KARMAD,SMAP,94.50,54.74,69.32,69.37,Reproduced,EasyTSAD implementation based on KARMAD paper

In [2]:
# Display clean table with "-" for missing values

metric_cols = ["Precision", "Recall", "F1", "AUPRC"]

df_display = df_stage2.copy()

for col in metric_cols:
    df_display[col] = df_display[col].apply(
        lambda x: "-" if pd.isna(x) else f"{x:.2f}"
    )

df_display = df_display.sort_values(
    ["Dataset", "F1"],
    ascending=[True, False],
    na_position="last"
).reset_index(drop=True)

df_display

,Model,Dataset,Precision,Recall,F1,AUPRC,Source,Note
0,DeepSKAN,MSL,91.58,93.27,92.42,90.47,Ours,Final proposed model
1,DLinear,MSL,90.95,86.60,88.72,91.48,Reproduced,EasyTSAD implementation
2,KARMAD,MSL,85.54,80.67,83.03,83.11,Reproduced,EasyTSAD implementation based on KARMAD paper
3,DeepSVDD,MSL,91.80,65.67,76.57,77.61,Reproduced,EasyTSAD reproduction
4,KAN-AD,MSL,53.10,66.73,46.33,36.67,Reproduced,Standalone KAN-AD
5,LSTM-AE,MSL,29.41,75.55,42.34,31.59,Reproduced,EasyTSAD implementation
6,DeepSKAN,SMAP,89.24,69.96,78.43,87.36,Ours,Final proposed model
7,DLinear,SMAP,71.80,71.10,71.45,80.77,Reproduced,EasyTSAD implementation
8,KARMAD,SMAP,94.50,54.74,69.32,69.37,Reproduced,EasyTSAD implementation based on KARMAD paper
9,LSTM-AE,SMAP,66.57,52.92,58.97,55.13,Reproduced,EasyTSAD implementation
10,KAN-AD,SMAP,91.59,44.91,57.04,50.15,Reproduced,Standalone KAN-AD
11,DeepSVDD,SMAP,13.63,89.63,23.65,15.23,Reproduced,PR-AUC used as AUPRC
12,DLinear,SWaT,95.53,95.77,95.65,97.98,Reproduced,EasyTSAD implementation
13,DeepSKAN,SWaT,93.52,96.69,95.08,98.10,Ours,Final proposed model
14,LSTM-AE,SWaT,94.05,79.33,86.06,86.70,Reproduced,EasyTSAD implementation
15,KARMAD,SWaT,90.68,77.96,83.84,86.65,Reproduced,EasyTSAD implementation based on KARMAD paper
16,KAN-AD,SWaT,73.05,89.59,74.15,69.33,Reproduced,Standalone KAN-AD
17,DeepSVDD,SWaT,26.11,84.73,39.92,24.29,Reproduced,EasyTSAD reproduction

In [3]:
# ==========================================================
# Highlight best and second-best values per dataset and metric
# Best = bold, Second-best = underline
# Missing values = "-"
# ==========================================================

metric_cols = ["Precision", "Recall", "F1", "AUPRC"]

def format_metric_table(group):
    group = group.copy()

    for metric in metric_cols:
        values = group[metric].dropna().sort_values(ascending=False).unique()

        best = values[0] if len(values) >= 1 else None
        second = values[1] if len(values) >= 2 else None

        formatted_values = []

        for x in group[metric]:
            if pd.isna(x):
                formatted_values.append("-")
            elif best is not None and np.isclose(x, best):
                formatted_values.append(r"\textbf{" + f"{x:.2f}" + "}")
            elif second is not None and np.isclose(x, second):
                formatted_values.append(r"\underline{" + f"{x:.2f}" + "}")
            else:
                formatted_values.append(f"{x:.2f}")

        group[metric] = formatted_values

    return group

df_latex_highlighted = (
    df_stage2
    .groupby("Dataset", group_keys=False)
    .apply(format_metric_table)
)

# Sort by dataset and F1, keeping missing values last
df_latex_highlighted["_F1_sort"] = df_stage2["F1"]

df_latex_highlighted = (
    df_latex_highlighted
    .sort_values(["Dataset", "_F1_sort"], ascending=[True, False], na_position="last")
    .drop(columns=["_F1_sort"])
    .reset_index(drop=True)
)

df_latex_highlighted

/tmp/ipykernel_19854/3390367967.py:37: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(format_metric_table)

,Model,Dataset,Precision,Recall,F1,AUPRC,Source,Note
0,DeepSKAN,MSL,\underline{91.58},\textbf{93.27},\textbf{92.42},\underline{90.47},Ours,Final proposed model
1,DLinear,MSL,90.95,\underline{86.60},\underline{88.72},\textbf{91.48},Reproduced,EasyTSAD implementation
2,KARMAD,MSL,85.54,80.67,83.03,83.11,Reproduced,EasyTSAD implementation based on KARMAD paper
3,DeepSVDD,MSL,\textbf{91.80},65.67,76.57,77.61,Reproduced,EasyTSAD reproduction
4,KAN-AD,MSL,53.10,66.73,46.33,36.67,Reproduced,Standalone KAN-AD
5,LSTM-AE,MSL,29.41,75.55,42.34,31.59,Reproduced,EasyTSAD implementation
6,DeepSKAN,SMAP,89.24,69.96,\textbf{78.43},\textbf{87.36},Ours,Final proposed model
7,DLinear,SMAP,71.80,\underline{71.10},\underline{71.45},\underline{80.77},Reproduced,EasyTSAD implementation
8,KARMAD,SMAP,\textbf{94.50},54.74,69.32,69.37,Reproduced,EasyTSAD implementation based on KARMAD paper
9,LSTM-AE,SMAP,66.57,52.92,58.97,55.13,Reproduced,EasyTSAD implementation
10,KAN-AD,SMAP,\underline{91.59},44.91,57.04,50.15,Reproduced,Standalone KAN-AD
11,DeepSVDD,SMAP,13.63,\textbf{89.63},23.65,15.23,Reproduced,PR-AUC used as AUPRC
12,DLinear,SWaT,\textbf{95.53},\underline{95.77},\textbf{95.65},\underline{97.98},Reproduced,EasyTSAD implementation
13,DeepSKAN,SWaT,93.52,\textbf{96.69},\underline{95.08},\textbf{98.10},Ours,Final proposed model
14,LSTM-AE,SWaT,\underline{94.05},79.33,86.06,86.70,Reproduced,EasyTSAD implementation
15,KARMAD,SWaT,90.68,77.96,83.84,86.65,Reproduced,EasyTSAD implementation based on KARMAD paper
16,KAN-AD,SWaT,73.05,89.59,74.15,69.33,Reproduced,Standalone KAN-AD
17,DeepSVDD,SWaT,26.11,84.73,39.92,24.29,Reproduced,EasyTSAD reproduction

In [4]:
# ==========================================================
# Journal-style grouped LaTeX table
# Rows: Models
# Column groups: Datasets
# Subcolumns: P, R, F1, AUPRC
# Best = bold, Second-best = underline
# Missing = "-"
# ==========================================================

import pandas as pd
import numpy as np

# ----------------------------------------------------------
# Stage 2 results
# Values are percentages.
# Missing values are np.nan and will be displayed as "-".
# MTAD-Kanformer was removed because AUPRC was not available
# under the same evaluation protocol.
# ----------------------------------------------------------

data = [
    # Model, Dataset, Precision, Recall, F1, AUPRC

    # Proposed model
    ["DeepSKAN", "SWaT", 93.52, 96.69, 95.08, 98.10],
    ["DeepSKAN", "MSL",  91.58, 93.27, 92.42, 90.47],
    ["DeepSKAN", "SMAP", 89.24, 69.96, 78.43, 87.36],

    # DeepSVDD alone
    ["DeepSVDD", "SWaT", 26.11, 84.73, 39.92, 24.29],
    ["DeepSVDD", "MSL",  91.80, 65.67, 76.57, 77.61],
    ["DeepSVDD", "SMAP", 13.63, 89.63, 23.65, 15.23],

    # KAN-AD
    ["KAN-AD", "SWaT", 73.05, 89.59, 74.15, 69.33],
    ["KAN-AD", "MSL",  53.10, 66.73, 46.33, 36.67],
    ["KAN-AD", "SMAP", 91.59, 44.91, 57.04, 50.15],

    # DLinear
    ["DLinear", "SWaT", 95.53, 95.77, 95.65, 97.98],
    ["DLinear", "MSL",  90.95, 86.60, 88.72, 91.48],
    ["DLinear", "SMAP", 71.80, 71.10, 71.45, 80.77],

    # LSTM Autoencoder
    ["LSTM-AE", "SWaT", 94.05, 79.33, 86.06, 86.70],
    ["LSTM-AE", "MSL",  29.41, 75.55, 42.34, 31.59],
    ["LSTM-AE", "SMAP", 66.57, 52.92, 58.97, 55.13],

    # KARMAD
    ["KARMAD", "SWaT", 90.68, 77.96, 83.84, 86.65],
    ["KARMAD", "MSL",  85.54, 80.67, 83.03, 83.11],
    ["KARMAD", "SMAP", 94.50, 54.74, 69.32, 69.37],
]

df_stage2_latex = pd.DataFrame(
    data,
    columns=["Model", "Dataset", "Precision", "Recall", "F1", "AUPRC"]
)

# ----------------------------------------------------------
# Table formatting
# ----------------------------------------------------------

metric_map = {
    "Precision": "P",
    "Recall": "R",
    "F1": "F1",
    "AUPRC": "AUPRC"
}

datasets_order = ["SWaT", "MSL", "SMAP"]

models_order = [
    "DeepSVDD",
    "KAN-AD",
    "DLinear",
    "LSTM-AE",
    "KARMAD",
    "DeepSKAN",
]

def format_best_second(df, dataset, metric, model):
    subset = df[df["Dataset"] == dataset][["Model", metric]].dropna()
    row = df[(df["Dataset"] == dataset) & (df["Model"] == model)]

    if row.empty or pd.isna(row.iloc[0][metric]):
        return "-"

    x = row.iloc[0][metric]
    value = f"{x:.2f}"

    values = np.sort(subset[metric].unique())[::-1]
    best = values[0] if len(values) >= 1 else None
    second = values[1] if len(values) >= 2 else None

    if best is not None and np.isclose(x, best):
        return r"\textbf{" + value + "}"
    elif second is not None and np.isclose(x, second):
        return r"\underline{" + value + "}"
    else:
        return value

# ----------------------------------------------------------
# Build grouped table
# ----------------------------------------------------------

rows = []

for model in models_order:
    row = {"Model": model}

    for dataset in datasets_order:
        for metric, short_name in metric_map.items():
            row[(dataset, short_name)] = format_best_second(
                df_stage2_latex,
                dataset,
                metric,
                model
            )

    rows.append(row)

df_grouped = pd.DataFrame(rows)

ordered_cols = ["Model"] + [
    (dataset, short_name)
    for dataset in datasets_order
    for short_name in metric_map.values()
]

df_grouped = df_grouped[ordered_cols]

multi_cols = [("", "Model")] + [
    (dataset, short_name)
    for dataset in datasets_order
    for short_name in metric_map.values()
]

df_grouped.columns = pd.MultiIndex.from_tuples(multi_cols)

df_grouped

                          SWaT                                        \
      Model                  P                  R                 F1
0  DeepSVDD              26.11              84.73              39.92
1    KAN-AD              73.05              89.59              74.15
2   DLinear     \textbf{95.53}  \underline{95.77}     \textbf{95.65}
3   LSTM-AE  \underline{94.05}              79.33              86.06
4    KARMAD              90.68              77.96              83.84
5  DeepSKAN              93.52     \textbf{96.69}  \underline{95.08}

                                    MSL                                        \
               AUPRC                  P                  R                 F1
0              24.29     \textbf{91.80}              65.67              76.57
1              69.33              53.10              66.73              46.33
2  \underline{97.98}              90.95  \underline{86.60}  \underline{88.72}
3              86.70              29.41              75.55              42.34
4              86.65              85.54              80.67              83.03
5     \textbf{98.10}  \underline{91.58}     \textbf{93.27}     \textbf{92.42}

                                   SMAP                                        \
               AUPRC                  P                  R                 F1
0              77.61              13.63     \textbf{89.63}              23.65
1              36.67  \underline{91.59}              44.91              57.04
2     \textbf{91.48}              71.80  \underline{71.10}  \underline{71.45}
3              31.59              66.57              52.92              58.97
4              83.11     \textbf{94.50}              54.74              69.32
5  \underline{90.47}              89.24              69.96     \textbf{78.43}


               AUPRC
0              15.23
1              50.15
2  \underline{80.77}
3              55.13
4              69.37
5     \textbf{87.36}

In [5]:
latex_table = df_grouped.to_latex(
    index=False,
    escape=False,
    multicolumn=True,
    multicolumn_format="c",
    column_format="l" + "c" * (len(datasets_order) * len(metric_map)),
    caption=r"Main benchmark comparison on SWaT, MSL, and SMAP. Best results are shown in bold and second-best results are underlined.",
    label="tab:main_benchmark_comparison"
)

print(latex_table)

\begin{table}
\caption{Main benchmark comparison on SWaT, MSL, and SMAP. Best results are shown in bold and second-best results are underlined.}
\label{tab:main_benchmark_comparison}
\begin{tabular}{lcccccccccccc}
\toprule
 & \multicolumn{4}{c}{SWaT} & \multicolumn{4}{c}{MSL} & \multicolumn{4}{c}{SMAP} \\
Model & P & R & F1 & AUPRC & P & R & F1 & AUPRC & P & R & F1 & AUPRC \\
\midrule
DeepSVDD & 26.11 & 84.73 & 39.92 & 24.29 & \textbf{91.80} & 65.67 & 76.57 & 77.61 & 13.63 & \textbf{89.63} & 23.65 & 15.23 \\
KAN-AD & 73.05 & 89.59 & 74.15 & 69.33 & 53.10 & 66.73 & 46.33 & 36.67 & \underline{91.59} & 44.91 & 57.04 & 50.15 \\
DLinear & \textbf{95.53} & \underline{95.77} & \textbf{95.65} & \underline{97.98} & 90.95 & \underline{86.60} & \underline{88.72} & \textbf{91.48} & 71.80 & \underline{71.10} & \underline{71.45} & \underline{80.77} \\
LSTM-AE & \underline{94.05} & 79.33 & 86.06 & 86.70 & 29.41 & 75.55 & 42.34 & 31.59 & 66.57 & 52.92 & 58.97 & 55.13 \\
KARMAD & 90.68 & 77.96 & 83.84 & 86.65 & 85.54 & 80.67 & 83.03 & 83.11 & \textbf{94.50} & 54.74 & 69.32 & 69.37 \\
DeepSKAN & 93.52 & \textbf{96.69} & \underline{95.08} & \textbf{98.10} & \underline{91.58} & \textbf{93.27} & \textbf{92.42} & \underline{90.47} & 89.24 & 69.96 & \textbf{78.43} & \textbf{87.36} \\
\bottomrule
\end{tabular}
\end{table}